server:
    port: 8081


spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest

    bootstrap-servers: localhost:9092

tpd:
  verification-result-topic: acct-verification-result-topic
  transfer-topic: transfer-topic